global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: eep
    static_configs:
      - targets: ['eep:8000']
    metrics_path: /metrics

  - job_name: iep1
    static_configs:
      - targets: ['iep1:8001']
    metrics_path: /metrics

  - job_name: iep2
    static_configs:
      - targets: ['iep2:8002']
    metrics_path: /metrics

  - job_name: iep3
    static_configs:
      - targets: ['iep3:8003']
    metrics_path: /metrics

  - job_name: iep4
    static_configs:
      - targets: ['iep4:8004']
    metrics_path: /metrics
