apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cedarfix-ingress
  namespace: cedarfix
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - host: cedarfix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
