"""Shared lexical policy for Arabizi OOV/drift handling.

Keep this module conservative: the goal is to surface meaningful unknown
municipal terms, not every connector, place name, acronym, or filler word.
Both the production probe and the offline OOV queue use these constants so
coverage/drift metrics do not silently disagree.
"""

STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "and",
        "at",
        "2adrou",
        "3ala",
        "3amel",
        "7all",
        "authority",
        "awlad",
        "b",
        "ba3d",
        "bass",
        "biddon",
        "bel",
        "bi",
        "bil",
        "bla",
        "btit7ammal",
        "by",
        "critique",
        "da",
        "e",
        "el",
        "est",
        "fi",
        "for",
        "from",
        "had",
        "halla2",
        "hay",
        "hayda",
        "hayde",
        "hon",
        "honik",
        "hunike",
        "in",
        "is",
        "jemb",
        "jiwar",
        "jouwwa",
        "kell",
        "kello",
        "ktir",
        "khali",
        "la",
        "l",
        "le",
        "ma",
        "mafi",
        "men",
        "mish",
        "mnee7a",
        "msh",
        "near",
        "on",
        "ou",
        "seyyara",
        "shi",
        "situation",
        "ta3",
        "ta3e",
        "talafonat",
        "the",
        "to",
        "w",
        "water",
        "we",
        "with",
        "ya",
        "yejib",
        "yemshi",
        "yi2flo",
        "ynamet",
    }
)

PROPER_OR_ENTITY_TOKENS: frozenset[str] = frozenset(
    {
        "7ammoud",
        "achrafieh",
        "armenia",
        "ashrafieh",
        "badaro",
        "beirut",
        "bliss",
        "bmlwe",
        "borj",
        "cd",
        "cdr",
        "edl",
        "hamra",
        "isf",
        "jemmayzeh",
        "jounieh",
        "mar",
        "mazraa",
        "mazra3a",
        "megastore",
        "mikhael",
        "moe",
        "raouche",
        "rass",
        "roushe",
        "sanayeh",
        "sa5ra",
        "saray",
        "verdun",
        "virgin",
        "wust",
    }
)

CONNECTORISH_SUFFIXES: tuple[str, ...] = ("na", "kon", "koun")

HIGH_RISK_HINTS: frozenset[str] = frozenset(
    {
        "5tr",
        "5atr",
        "5atar",
        "khatar",
        "m5atr",
        "sa32",
        "saa2",
        "nnar",
        "ghaz",
        "7ariki",
        "7ar2",
        "7are2",
        "masalla7",
        "mshbouh",
    }
)

IGNORED_OOV_TOKENS: frozenset[str] = STOPWORDS | PROPER_OR_ENTITY_TOKENS
